name: GitHub Profile Summary Cards

on:
  schedule:
    # Berjalan otomatis setiap hari jam 00:00 UTC
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-cards
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: vn7n24fzkq/github-profile-summary-cards@v2.5.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
